version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:1.71.0-bullseye
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - ../pallet-chainlink-feed:/var/www/pallet-chainlink-feed
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-template --dev --ws-external"
