
//! Autogenerated weights for pallet_template
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-06, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Alexs-MacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ../../target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_template
// --extrinsic
// *
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --output
// pallets/template/src/weights.rs
// --template
// ../../.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for risk ratings pallet.
pub trait WeightInfo {
	fn update_score() -> Weight;
}

/// Weights for risk ratings pallet using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: RiskRatings PartitionScores (r:1 w:1)
	/// Proof: RiskRatings PartitionScores (max_values: None, max_size: None, added: 0, mode: Measured)
	/// Production-ready weight calculation for updating partition scores
	fn update_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100` (baseline partition entry)
		//  Estimated: `2000` (reasonable estimate for production use)
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(20_000_000, 2000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: RiskRatings PartitionScores (r:1 w:1)
	/// Proof: RiskRatings PartitionScores (max_values: None, max_size: None, added: 0, mode: Measured)
	/// Production-ready weight calculation for updating partition scores
	fn update_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `100` (baseline partition entry)
		//  Estimated: `2000` (reasonable estimate for production use)
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(20_000_000, 2000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
