version: "3.9"

services:
  testnet-node:
    container_name: "testnet-node"
    image: ghcr.io/xerberusteam/xerberus-node:full-node-latest
    pull_policy: always
    restart: unless-stopped
    command: |
      --base-path /data/nodes/testnet-node
      --chain /data/chain-spec.json
      --rpc-external
      --rpc-methods Unsafe
      --rpc-cors all
      --telemetry-url "wss://telemetry.polkadot.io/submit/ 0"
      --prometheus-external
      --no-private-ip
      --sync fast
      --bootnodes /dns/node.xerberus.io/tcp/30334/ws/p2p/12D3KooWCYKbsQw2r5575MA8YqMhn8AqhVuZkfobPMyoKzEP595t/p2p/12D3KooWCYKbsQw2r5575MA8YqMhn8AqhVuZkfobPMyoKzEP595t
    ports:
      - "9944:9944"
      - "9933:9933"
      - "9615:9615"
      - "9930:9930"
      - "9333:9333"
      - "30333:30333"
      - "30334:30334"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "5"