name: Rust Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        chmod +x ./scripts/build.sh
        ./scripts/build.sh --cwd ${{ github.workspace }} --namespace ${{ github.actor }} --platform linux/amd64

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      run: |
        chmod +x ./scripts/publish.sh
        ./scripts/publish.sh --cwd ${{ github.workspace }} --namespace ${{ github.actor }}
